#!/bin/bash
for i in 8000
do
		echo -ne "   #### testing " $i "\n"
# hedcuter [-n #_of_disks -radius disk_radius -uniform_radius 
#            -iteration #_of_CVT_iterations -maxD max_CVF_site_displacement] image_file_name
		hedcuter -n $i images/bowtie.png
		mv "bowtie-"$i".svg" "output/hc_bowtie-"$i".svg"
done
