#!/bin/bash
for i in 8000 8000 8000 800
do
		echo -ne "   #### testing " $i "\n"
# hedcuter [-n #_of_disks -radius disk_radius -uniform_radius 
#            -iteration #_of_CVT_iterations -maxD max_CVF_site_displacement] image_file_name
		hedcuter -n $i -radius 1 images/Abraham_Lincoln_November_1863.png
done
