#!/bin/bash
for i in 1000 2000 4000 8000
do
	for j in 1 5 10
		do
			echo -ne "   #### testing " $i "\n"
			vs -s $i -f -z $j -n images/Abraham_Lincoln_November_1863.png "output/var/vr_AL_"$i"_var_r"$j".svg"
	done		
done

# vs -s 8000 -f -z 10 images/Abraham_Lincoln_November_1863.png output/multi/vr_AL_8000_r10_fixed.svg
